web:
  build: web
  restart: always
  environment:
    P2K16_DB_URL: "postgresql://p2k16:thisIsMy1stSecretCMSdbpwd@postgres/p2k16"
    FLASK_DEBUG: "1"
    SECRET_KEY: 'secret key'
  ports:
    - "5000:5000"
  links:
    - postgres
  volumes:
    - "$PWD/web:/usr/src/app"
postgres:
  build: docker/postgres
  restart: always
  environment:
    POSTGRES_PASSWORD: changethis_masterpostgres_pwd
    P2K16_DB_PASSWORD: thisIsMy1stSecretCMSdbpwd
  labels:
    io.enonic.backup.enable: "yes"
    io.enonic.backup.prescripts: "/usr/local/bin/backup-pre.sh"
    io.enonic.backup.postscripts: "/usr/local/bin/backup-post.sh"
    io.enonic.backup.data: "/backup"
  volumes_from:
    - postgresstorage
postgresstorage:
  image: postgres:9.4.1
  command: "echo Postgres storage container"
  volumes:
    - /var/lib/postgresql/data
#mail:
#  image: enoniccloud/postfix
#  hostname: SITE_HOSTNAME
#  restart: always