version: '2'

services:
  mqtt:
    image: drerik/mosquitto:1.4.11
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - "mqtt-data:/var/lib/mosquitto/"
  web:
    build: web
    restart: always
    environment:
      P2K16_DB_URL: "postgresql://p2k16:thisIsMy1stSecretCMSdbpwd@postgres/p2k16"
      FLASK_DEBUG: "1"
      SECRET_KEY: 'secret key'
      P2K16_CONFIG: '/usr/src/app/config-docker.cfg'
    ports:
      - "5000:5000"
    links:
      - postgres
      #- mqtt:mqtt.bitraf.no
      - mail
    volumes:
      - "$PWD/web:/usr/src/app"
  mail:
    image: enoniccloud/postfix
    hostname: bomba.bitraf.no
    restart: always
  postgres:
    build: docker/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: changethis_masterpostgres_pwd
      P2K16_DB_PASSWORD: thisIsMy1stSecretCMSdbpwd
    labels:
      io.enonic.backup.enable: "yes"
      io.enonic.backup.prescripts: "/usr/local/bin/backup-pre.sh"
      io.enonic.backup.postscripts: "/usr/local/bin/backup-post.sh"
      io.enonic.backup.data: "/backup"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
volumes:
    mqtt-data:
    postgres-data:
